name: pmforms-demo
main: dktapps\pmforms_demo\Main
version: 0.0.1
api: [4.0.0, 5.0.0]
load: POSTWORLD
author: dktapps
description: Demo plugin that shows off in-game forms, and how to use its API via code
website: https://github.com/dktapps-pm-pl/pmforms-demo
commands:
  form:
    description: "Allows sending an example form to the target player"
    usage: "/form <modal|menu|custom> [players ...]"
    permission: pmforms.command
permissions:
  pmforms.command:
    default: true
    description: "Allows the use of /form"
